//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elysium.Platform.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF1BA1E2")]
        public global::System.Windows.Media.Color AccentColor {
            get {
                return ((global::System.Windows.Media.Color)(this["AccentColor"]));
            }
            set {
                this["AccentColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Dark")]
        public global::Elysium.Theme.WPF.Theme Theme {
            get {
                return ((global::Elysium.Theme.WPF.Theme)(this["Theme"]));
            }
            set {
                this["Theme"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ObservableDictionaryOfGuidGadget xmlns:" +
            "xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/200" +
            "1/XMLSchema\" />")]
        public global::Elysium.Platform.Collections.ObservableDictionary<System.Guid, Elysium.Platform.Entities.Gadget> Gadgets {
            get {
                return ((global::Elysium.Platform.Collections.ObservableDictionary<System.Guid, Elysium.Platform.Entities.Gadget>)(this["Gadgets"]));
            }
            set {
                this["Gadgets"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ObservableDictionaryOfGuidApplication x" +
            "mlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.or" +
            "g/2001/XMLSchema\" />")]
        public global::Elysium.Platform.Collections.ObservableDictionary<System.Guid, Elysium.Platform.Entities.Application> Applications {
            get {
                return ((global::Elysium.Platform.Collections.ObservableDictionary<System.Guid, Elysium.Platform.Entities.Application>)(this["Applications"]));
            }
            set {
                this["Applications"] = value;
            }
        }
    }
}
