//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elysium.SDK.MSI.UI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Elysium.SDK.MSI.UI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I agree to the License terms and conditions..
        /// </summary>
        public static string Agreement {
            get {
                return ResourceManager.GetString("Agreement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applying:.
        /// </summary>
        public static string Applying {
            get {
                return ResourceManager.GetString("Applying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ....
        /// </summary>
        public static string Browse {
            get {
                return ResourceManager.GetString("Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation has been cancelled..
        /// </summary>
        public static string Canceled {
            get {
                return ResourceManager.GetString("Canceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to cancel?.
        /// </summary>
        public static string CancellationWarning {
            get {
                return ResourceManager.GetString("CancellationWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English documentation.
        /// </summary>
        public static string Documentation_en {
            get {
                return ResourceManager.GetString("Documentation_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Russian documentation.
        /// </summary>
        public static string Documentation_ru {
            get {
                return ResourceManager.GetString("Documentation_ru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A newer version of Elysium SDK is already installed..
        /// </summary>
        public static string Downgrade {
            get {
                return ResourceManager.GetString("Downgrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download location:.
        /// </summary>
        public static string DownloadLocation {
            get {
                return ResourceManager.GetString("DownloadLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation failed..
        /// </summary>
        public static string Failed {
            get {
                return ResourceManager.GetString("Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish.
        /// </summary>
        public static string Finish {
            get {
                return ResourceManager.GetString("Finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always restart the system after installation..
        /// </summary>
        public static string HelpForceRestart {
            get {
                return ResourceManager.GetString("HelpForceRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display this usage text..
        /// </summary>
        public static string HelpHelp {
            get {
                return ResourceManager.GetString("HelpHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup language.
        /// </summary>
        public static string HelpLanguage {
            get {
                return ResourceManager.GetString("HelpLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a copy of the media in specified folder..
        /// </summary>
        public static string HelpLayout {
            get {
                return ResourceManager.GetString("HelpLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies a location for the log file..
        /// </summary>
        public static string HelpLog {
            get {
                return ResourceManager.GetString("HelpLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify the product features configuration..
        /// </summary>
        public static string HelpModify {
            get {
                return ResourceManager.GetString("HelpModify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not restart during or after installation..
        /// </summary>
        public static string HelpNoRestart {
            get {
                return ResourceManager.GetString("HelpNoRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display progress but do not wait for user input..
        /// </summary>
        public static string HelpPassive {
            get {
                return ResourceManager.GetString("HelpPassive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prompt the user before restarting the system..
        /// </summary>
        public static string HelpPromptRestart {
            get {
                return ResourceManager.GetString("HelpPromptRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quiet mode with no display and no user interaction..
        /// </summary>
        public static string HelpQuiet {
            get {
                return ResourceManager.GetString("HelpQuiet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repair the product..
        /// </summary>
        public static string HelpRepair {
            get {
                return ResourceManager.GetString("HelpRepair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This setup supports the following switches:.
        /// </summary>
        public static string HelpTitle {
            get {
                return ResourceManager.GetString("HelpTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstall the product..
        /// </summary>
        public static string HelpUninstall {
            get {
                return ResourceManager.GetString("HelpUninstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install.
        /// </summary>
        public static string Install {
            get {
                return ResourceManager.GetString("Install", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination folder:.
        /// </summary>
        public static string InstallFolder {
            get {
                return ResourceManager.GetString("InstallFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installer will install Elysium SDK to:.
        /// </summary>
        public static string InstallTo {
            get {
                return ResourceManager.GetString("InstallTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License terms.
        /// </summary>
        public static string LicenseLink {
            get {
                return ResourceManager.GetString("LicenseLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  before you can install the product..
        /// </summary>
        public static string LicenseTextAfterLink {
            get {
                return ResourceManager.GetString("LicenseTextAfterLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must agree to the .
        /// </summary>
        public static string LicenseTextBeforeLink {
            get {
                return ResourceManager.GetString("LicenseTextBeforeLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify.
        /// </summary>
        public static string Modify {
            get {
                return ResourceManager.GetString("Modify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .NET Framework 4.
        /// </summary>
        public static string NETFrameworkName {
            get {
                return ResourceManager.GetString("NETFrameworkName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications system.
        /// </summary>
        public static string Notifications {
            get {
                return ResourceManager.GetString("Notifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to reboot to complete operation..
        /// </summary>
        public static string Reboot {
            get {
                return ResourceManager.GetString("Reboot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I want to manually reboot later.
        /// </summary>
        public static string RebootLater {
            get {
                return ResourceManager.GetString("RebootLater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reboot now.
        /// </summary>
        public static string RebootNow {
            get {
                return ResourceManager.GetString("RebootNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repair.
        /// </summary>
        public static string Repair {
            get {
                return ResourceManager.GetString("Repair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elysium SDK.
        /// </summary>
        public static string SDKName {
            get {
                return ResourceManager.GetString("SDKName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.5.
        /// </summary>
        public static string SDKVersion {
            get {
                return ResourceManager.GetString("SDKVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select all.
        /// </summary>
        public static string SelectAll {
            get {
                return ResourceManager.GetString("SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation successfully completed..
        /// </summary>
        public static string Successful {
            get {
                return ResourceManager.GetString("Successful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample application.
        /// </summary>
        public static string Test {
            get {
                return ResourceManager.GetString("Test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstall.
        /// </summary>
        public static string Uninstall {
            get {
                return ResourceManager.GetString("Uninstall", resourceCulture);
            }
        }
    }
}
